version: '3'

services:

 nginx:
  container_name: nginx
  build:
   context: ./requirements/nginx
   dockerfile: Dockerfile
  ports:
   - 443:443
  volumes:
   - wordpress:/var/www/wordpress
  networks:
   - inception
  restart: always

 mariadb:
  container_name: mariadb
  build:
   context: ./requirements/mariadb
   dockerfile: Dockerfile
  env_file:
   - .env
  volumes:
   - db:/var/lib/mysql
  networks:
   - inception
  restart: always

 wordpress:
  container_name: wordpress
  depends_on:
   - mariadb
  build:
   context: ./requirements/wordpress
   dockerfile: Dockerfile
  env_file:
   - .env
  volumes:
   - wordpress:/var/www/wordpress
  networks:
   - inception
  restart: always

 ftp:
  container_name: ftp
  build:
    context: ./requirements/ftp
    dockerfile: Dockerfile
  ports:
    - "21:21"
    - "30000-30009:30000-30009"  # Pour les connexions passives
  environment:
    - FTP_USER=${FTP_USER}
    - FTP_PASS=${FTP_PASS}
  volumes:
    - wordpress:/home/${FTP_USER}/wordpress  # Lier au volume de WordPress
  networks:
    - inception
  restart: always


  # ftp:
  #   container_name: ftp
  #   build:
  #    context: ./requirements/ftp
  #    dockerfile: Dockerfile
  #   env_file:
  #     - .env
  #   ports:
  #     - 21:21
  #     - 30000-30009:30000-30009
  #   volumes:
  #     - wordpress:/home/ftp_user/wordpress
  #   networks:
  #     - inception
  #   restart: always

networks:
 inception:
  driver: bridge

volumes:
 wordpress:
  driver: local
  driver_opts:
   type: none
   device: /home/smortemo/data/wordpress
   o: bind
 db:
  driver: local
  driver_opts:
   type: none
   device: /home/smortemo/data/mariadb
   o: bind

